version: '2'
services:
  jenkins:
    build: ./Dockerfile
    image: jenkins-tuta
    container_name: jenkins_master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
